# This is a sample TOML control file for the ScriptedBibleEditor
#
# Available commands are:
#
#   title = "My Control File Title"
#   description = "A longer description"
#
#   [commandTables]
#   tableName = "filepath"
#

title = "ScriptedBibleEditor Sample Control File"
description = "To convert USFM files to create the draft OET-LV"

inputFolder = "../../TestFiles/source_YLT_USFM/"
inputFilenameTemplate = "BBB_gloss.usfm"

outputFolder = "../../TestFiles/modernised_YLT_USFM/"
createOutputFolder = true
clearOutpuFolder = true

applyOrder = "AllTablesFirst"

# Command tables are applied in the given order
[commandTables]
wordingAdjustments = "wordingAdjustments.commandTable.tsv"
#adjustCapitalisation = "adjustCapitalisation.commandTable.tsv"
#changeFromUSSpelling = "changeFromUSSpelling.commandTable.tsv"
OTNames = "OTNames.commandTable.tsv"
NTNames = "NTNames.commandTable.tsv"
#adjustPunctuation = "adjustPunctuation.commandTable.tsv"
#cleanupYLT = "cleanupYLT.commandTable.tsv"
